- app/components/App.js
- app/scenes/CameraScene.js
- app/scenes/CapturedScene.js
Add a scene to confirm whether the user wants to use the taken photo.
> Captured scene

- app/components/App.js
- app/scenes/LandingScene.js
- app/scenes/TreeDescriptionScene.js
- app/scenes/formScene.js
Simple tree description scene, accessed by clicking each landing scene tree card.
> Add description scene

- android/app/build.gradle
- android/app/src/main/java/com/wildtype/MainApplication.java
- android/settings.gradle
- app/components/App.js
- app/components/GetLocation.js
- app/components/Header.js
- app/db/Schema.js
- app/scenes/CameraScene.js
- app/scenes/CaptureLocationScene.js
- app/scenes/CapturedScene.js
- app/scenes/FormScene.js
- app/scenes/LandingScene.js
- app/scenes/SubmittedScene.js
- app/scenes/TreeDescriptionScene.js
- ios/WildType.xcodeproj/project.pbxproj
- package.json
- yarn.lock
Fixed conflict between fix-routing and formValidation branches.
> Fix routing

- app/components/GetLocation.js
- app/scenes/CapturedScene.js
- app/scenes/FormScene.js
> Revert to Async for form data

- app/components/App.js
- app/resources/config.js
- app/scenes/CameraScene.js
- app/scenes/CapturedScene.js
- app/scenes/FormScene.js
Only need to refine the form to accept multiple images.
> Camera (Almost Done)

- app/components/Form.js
- app/components/PickerModal.js
- app/resources/config.js
The white oak branch height question was "tap to enter diameter".  Now we can pass in a props
> add a props for the placeholder text

- app/resources/config.js
> add ash id photos to ash question modal issue 340

- package-lock.json
- package.json
@bradfordcondon to test the fix you have to run `npm i` so that it pulls our fork of the repo
> Fix images using a fork from rn-photo-view

- app/helpers/Observation.js
This PR addresses the issue with duplicate submissions by sending observation details in increments and saving the state of the upload.
> Fix submissions of duplicates

- app/components/AdvancedSettingsModal.js
- app/components/Form.js
- app/db/Schema.js
- app/helpers/Observation.js
- app/screens/SubmittedScreen.js
I am not going to merge this until we have a full implementation on the web side.
> Add private observation button and fix issue #424

- app/screens/ObservationScreen.js
- app/screens/ObservationsScreen.js
> use treesnap twitter handle in tweet message

- app/resources/descriptions.js
Minor fixes in the about description screens requested in #469 #474
> fix minor typo and fix link in descriptions

- app/screens/CameraScreen.js
- index.js
> Camera enhancements

- .babelrc
- .gitignore
- App.js
- __tests__/Errors.test.js
- android/build.gradle
- android/gradle.properties
- app/components/Form.js
- app/components/ObservationLostImagesFixer.js
- app/db/Schema.js
- app/helpers/Diagnostics.js
- app/helpers/Errors.js
- app/helpers/File.js
- app/helpers/ImageUploadTracker.js
- app/helpers/Images.js
- app/helpers/Observation.js
- app/screens/LandingScreen.js
- app/screens/ObservationScreen.js
- ios/Treesnap.xcodeproj/xcshareddata/xcschemes/Treesnap.xcscheme
- package-lock.json
- package.json
This PR creates a component that will inform the user of the deleted images if any are found and allow them to re-download the missing images and discard broken image paths from observation details so upload errors don't occur.
This does pretty risky operations so before merging and releasing it, I'll need to do some testing and reviewing with a clear mind.
> Re-download broken observations

- app/components/Location.js
- package-lock.json
in response to [#532](https://github.com/statonlab/Treesnap-mobile/issues/532)
> latitude and longitude examples fixed

- App.js
- android/app/build.gradle
- app/routes/Navigator.js
- app/screens/LandingScreen.js
- ios/Treesnap.xcodeproj/project.pbxproj
- ios/Treesnap.xcodeproj/xcshareddata/xcschemes/Treesnap.xcscheme
- ios/Treesnap/AppDelegate.m
- ios/Treesnap/Info.plist
- package.json
We had an issue where iPhone users would reject location services automatically. The app now does not allow that to happen and actually waits for the user to respond.
> Fix location permissions

- app/components/AutoComplete.js
- package-lock.json
- package.json
> fixed a warning with autocomplete

- app/components/Form.js
- app/components/PickerModal.js
#584 
> One last thing for this. Let's round to 2 decimal points in `onBlur` only of the compute from circumference is added. New branch please.
> computing circumference rounds to 2 decimal places

- __tests__/__snapshots__/config.test.js.snap
- app/resources/Descriptions.js
- app/resources/FormElements.js
- app/resources/ValidationRules.js
> Planted vs. Wild

- __tests__/__snapshots__/config.test.js.snap
- app/resources/FormElements.js
- package-lock.json
> updated height of first branch question

- app/components/Form.js
> Changed form submit button to save

- app/components/CustomIDModal.js
- app/components/Form.js
- app/screens/ObservationsScreen.js
> Fix multiple bugs

- app/components/Form.js
- app/db/Schema.js
- app/helpers/Observation.js
- app/screens/ObservationsScreen.js
Fixes the sort issue and attempts to fix the sync issue #606 
Since I can't replicate the sync issue, I am not sure how to fix it exactly but let's publish and have Marysol try again.
> Fix sort and sync issue

- app/resources/TreeLatinNames.js
> Added new species to the other trees list

- app/resources/FormElements.js
> Added not sure option to hybrid attributes question
